### ISSUE TITLE
auxiliary files

### ISSUE THREAD

**Issue by SzotsGabor** [Dragjon/Nectar#3]
As I can see, the screlu files have been changed which means that I must install 0.1.8 in another folder, separated from 0.1.4, if I want to use both. Some more versions and my PC will have several Nectar folders, which I would not have. Could it not be avoided?

**Comment by Dragjon** [comment]
I could rename the weights and biases files to a specific version if that helps

**Comment by SzotsGabor** [comment]
> I could rename the weights and biases files to a specific version if that helps

Of course it would. Good idea, thanks.

**Comment by Dragjon** [comment]
I have renamed the weights and biases already and patched the release for 0.1.8
From now on, every re-training of model will include a new id for their weights and biases. If different versions use the same model (weights and biases), the id would be the same

**Comment by SzotsGabor** [comment]
> I have renamed the weights and biases already and patched the release for 0.1.8 From now on, every re-training of model will include a new id for their weights and biases. If different versions use the same model (weights and biases), the id would be the same

Excellent! Thank you.
